services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: dev-colab-fe.bnitech.online
    restart: unless-stopped
    ports:
      - "${PORT:-4322}:4322"
    environment:
      - NODE_ENV=development
      - HOST=0.0.0.0
      - PORT=4322
      - PUBLIC_API_URL=${PUBLIC_API_URL:-http://localhost:3002/api/v1}
    networks:
      - bni-colab-net-dev

networks:
  bni-colab-net-dev:
    driver: bridge
