services:
  colab-fe-prod_bnitech_online:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: colab-fe-prod_bnitech_online
    restart: unless-stopped
    ports:
      - "4322"
    environment:
      - PUBLIC_API_URL=${PUBLIC_API_URL:-http://colab-be-prod.bnitech.online:3002/api/v1}