services:
  colab-fe-dev.bnitech.online:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: colab-fe-dev.bnitech.online
    restart: unless-stopped
    ports:
      - "4322"
    environment:
      - NODE_ENV=development
      - HOST=0.0.0.0
      - PORT=4322
      - PUBLIC_API_URL=${PUBLIC_API_URL:-http://colab-be-dev.bnitech.online:3002/api/v1}
    networks:
      - bni-colab-net-dev
      
networks:
  bni-colab-net-dev:
    driver: bridge