services:
  colab-fe-prod_bnitech_online:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: colab-fe-prod_bnitech_online
    restart: unless-stopped
    expose:
      - "4322"
    environment:
      - PUBLIC_API_URL=${PUBLIC_API_URL:-https://colab.bnitech.online/api/v1}
    networks:
      coolify:
        aliases:
          - colab-fe-prod_bnitech_online

networks:
  coolify:
    external: true
    name: coolify
